apiVersion: v1
kind: Service
metadata:
  name: api-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443      
  selector:
    app: api